services:
    shipmonk-packing-mysql:
        image: mariadb:10.10
        ports:
            -
                target: 3306
                published: 3307
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: packing
        hostname: mysql

    shipmonk-packing-app:
        depends_on:
            - shipmonk-packing-mysql
        build: .
        working_dir: /app
        user: ${UID:-1000}:${GID:-1000}
        volumes:
          - .:/app
        environment:
            BIN_PACKING_USERNAME: ${BIN_PACKING_USERNAME}
            BIN_PACKING_APIKEY: ${BIN_PACKING_APIKEY}
            BIN_PACKING_URL: https://global-api.3dbinpacking.com/packer/packIntoMany

    shipmonk-packing-nginx:
        image: nginx:stable-alpine
        ports:
            - "8081:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/app
        depends_on:
            - shipmonk-packing-app
    
    shipmonk-packing-adminer:
        depends_on:
            - shipmonk-packing-mysql
        image: adminer:latest
        ports:
            -
                target: 8080
                published: 8080
